version: "3.8"
services:
  mysql:
    image: mysql:8.4.3
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movies_DB
      MYSQL_USER: recsys
      MYSQL_PASSWORD: recsys
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: